config/routes.rb
    get "capabilities" => "capabilities#show" # Deprecated, remove when 0.6 support is removed
    get "versions" => "versions#show"
  end

  scope "api/0.6" do
    get "capabilities" => "api/capabilities#show"
    get "permissions" => "api/permissions#show"

    put "changeset/create" => "api/changesets#create"
    post "changeset/:id/upload" => "api/changesets#upload", :id => /\d+/
    get "changeset/:id/download" => "api/changesets#download", :as => :changeset_download, :id => /\d+/
    get "changeset/:id" => "api/changesets#show", :as => :changeset_show, :id => /\d+/
    post "changeset/:id/subscribe" => "api/changesets#subscribe", :as => :changeset_subscribe, :id => /\d+/
    post "changeset/:id/unsubscribe" => "api/changesets#unsubscribe", :as => :changeset_unsubscribe, :id => /\d+/
    put "changeset/:id" => "api/changesets#update", :id => /\d+/
    put "changeset/:id/close" => "api/changesets#close", :id => /\d+/
    get "changesets" => "api/changesets#query"
    post "changeset/:id/comment" => "api/changeset_comments#create", :as => :changeset_comment, :id => /\d+/
    post "changeset/comment/:id/hide" => "api/changeset_comments#destroy", :as => :changeset_comment_hide, :id => /\d+/
    post "changeset/comment/:id/unhide" => "api/changeset_comments#restore", :as => :changeset_comment_unhide, :id => /\d+/

    put "node/create" => "api/nodes#create"
    get "node/:id/ways" => "api/ways#ways_for_node", :id => /\d+/
    get "node/:id/relations" => "api/relations#relations_for_node", :id => /\d+/
    get "node/:id/history" => "api/old_nodes#history", :id => /\d+/
    post "node/:id/:version/redact" => "api/old_nodes#redact", :version => /\d+/, :id => /\d+/
    get "node/:id/:version" => "api/old_nodes#version", :id => /\d+/, :version => /\d+/
    get "node/:id" => "api/nodes#show", :id => /\d+/
    put "node/:id" => "api/nodes#update", :id => /\d+/
    delete "node/:id" => "api/nodes#delete", :id => /\d+/
    get "nodes" => "api/nodes#index"

    put "way/create" => "api/ways#create"
    get "way/:id/history" => "api/old_ways#history", :id => /\d+/
    get "way/:id/full" => "api/ways#full", :id => /\d+/
    get "way/:id/relations" => "api/relations#relations_for_way", :id => /\d+/
    post "way/:id/:version/redact" => "api/old_ways#redact", :version => /\d+/, :id => /\d+/
    get "way/:id/:version" => "api/old_ways#version", :id => /\d+/, :version => /\d+/
    get "way/:id" => "api/ways#show", :id => /\d+/
    put "way/:id" => "api/ways#update", :id => /\d+/
    delete "way/:id" => "api/ways#delete", :id => /\d+/
    get "ways" => "api/ways#index"

    put "relation/create" => "api/relations#create"
    get "relation/:id/relations" => "api/relations#relations_for_relation", :id => /\d+/
    get "relation/:id/history" => "api/old_relations#history", :id => /\d+/
    get "relation/:id/full" => "api/relations#full", :id => /\d+/
    post "relation/:id/:version/redact" => "api/old_relations#redact", :version => /\d+/, :id => /\d+/
    get "relation/:id/:version" => "api/old_relations#version", :id => /\d+/, :version => /\d+/
    get "relation/:id" => "api/relations#show", :id => /\d+/
    put "relation/:id" => "api/relations#update", :id => /\d+/
    delete "relation/:id" => "api/relations#delete", :id => /\d+/
    get "relations" => "api/relations#index"

    get "map" => "api/map#index"

    get "trackpoints" => "api/tracepoints#index"

    get "changes" => "api/changes#index"

    get "user/:id" => "api/users#show", :id => /\d+/
    get "user/details" => "api/users#details"
    get "user/gpx_files" => "api/users#gpx_files"
    get "users" => "api/users#index", :as => :api_users

    get "user/preferences" => "api/user_preferences#index"
    get "user/preferences/:preference_key" => "api/user_preferences#show"
    put "user/preferences" => "api/user_preferences#update_all"
    put "user/preferences/:preference_key" => "api/user_preferences#update"
    delete "user/preferences/:preference_key" => "api/user_preferences#destroy"

    post "gpx/create" => "api/traces#create"
    get "gpx/:id" => "api/traces#show", :id => /\d+/
    put "gpx/:id" => "api/traces#update", :id => /\d+/
    delete "gpx/:id" => "api/traces#destroy", :id => /\d+/
    get "gpx/:id/details" => "api/traces#show", :id => /\d+/
    get "gpx/:id/data" => "api/traces#data"

    # AMF (ActionScript) API
    post "amf/read" => "api/amf#amf_read"
    post "amf/write" => "api/amf#amf_write"

    # Map notes API
    resources :notes, :except => [:new, :edit, :update], :constraints => { :id => /\d+/ }, :defaults => { :format => "xml" }, :controller => "api/notes" do
      collection do
        get "search"
        get "feed", :defaults => { :format => "rss" }
      end

      member do
        post "comment"
        post "close"
        post "reopen"
      end
    end

    post "notes/addPOIexec" => "api/notes#create"
    post "notes/closePOIexec" => "api/notes#close"
    post "notes/editPOIexec" => "api/notes#comment"
    get "notes/getGPX" => "api/notes#index", :format => "gpx"
    get "notes/getRSSfeed" => "api/notes#feed", :format => "rss"
  end

  # Data browsing
  get "/way/:id" => "browse#way", :id => /\d+/, :as => :way
  get "/way/:id/history" => "browse#way_history", :id => /\d+/
  get "/node/:id" => "browse#node", :id => /\d+/, :as => :node
  get "/node/:id/history" => "browse#node_history", :id => /\d+/
  get "/relation/:id" => "browse#relation", :id => /\d+/, :as => :relation
  get "/relation/:id/history" => "browse#relation_history", :id => /\d+/
  get "/changeset/:id" => "browse#changeset", :as => :changeset, :id => /\d+/
  get "/changeset/:id/comments/feed" => "changeset_comments#index", :as => :changeset_comments_feed, :id => /\d*/, :defaults => { :format => "rss" }
  get "/note/:id" => "browse#note", :id => /\d+/, :as => "browse_note"
  get "/note/new" => "browse#new_note"
  get "/user/:display_name/history" => "changesets#index"
  get "/user/:display_name/history/feed" => "changesets#feed", :defaults => { :format => :atom }
  get "/user/:display_name/notes" => "notes#mine"
  get "/history/friends" => "changesets#index", :friends => true, :as => "friend_changesets", :defaults => { :format => :html }
  get "/history/nearby" => "changesets#index", :nearby => true, :as => "nearby_changesets", :defaults => { :format => :html }

  get "/browse/way/:id",                :to => redirect(:path => "/way/%{id}")
  get "/browse/way/:id/history",        :to => redirect(:path => "/way/%{id}/history")
  get "/browse/node/:id",               :to => redirect(:path => "/node/%{id}")
  get "/browse/node/:id/history",       :to => redirect(:path => "/node/%{id}/history")
  get "/browse/relation/:id",           :to => redirect(:path => "/relation/%{id}")
  get "/browse/relation/:id/history",   :to => redirect(:path => "/relation/%{id}/history")
  get "/browse/changeset/:id",          :to => redirect(:path => "/changeset/%{id}")
  get "/browse/note/:id",               :to => redirect(:path => "/note/%{id}")
  get "/user/:display_name/edits",      :to => redirect(:path => "/user/%{display_name}/history")
  get "/user/:display_name/edits/feed", :to => redirect(:path => "/user/%{display_name}/history/feed")
  get "/browse/friends",                :to => redirect(:path => "/history/friends")
  get "/browse/nearby",                 :to => redirect(:path => "/history/nearby")
  get "/browse/changesets/feed",        :to => redirect(:path => "/history/feed")
  get "/browse/changesets",             :to => redirect(:path => "/history")
  get "/browse",                        :to => redirect(:path => "/history")

  # web site
  root :to => "site#index", :via => [:get, :post]
  get "/edit" => "site#edit"
  get "/copyright/:copyright_locale" => "site#copyright"
  get "/copyright" => "site#copyright"
  get "/welcome" => "site#welcome"
  get "/fixthemap" => "site#fixthemap"
  get "/help" => "site#help"
  get "/about" => "site#about"
  get "/history" => "changesets#index"
  get "/history/feed" => "changesets#feed", :defaults => { :format => :atom }
  get "/history/comments/feed" => "changeset_comments#index", :as => :changesets_comments_feed, :defaults => { :format => "rss" }
  get "/export" => "site#export"
  match "/login" => "users#login", :via => [:get, :post]
  match "/logout" => "users#logout", :via => [:get, :post]
  get "/offline" => "site#offline"
  get "/key" => "site#key"
  get "/id" => "site#id"
  get "/query" => "browse#query"
  get "/user/new" => "users#new"
  post "/user/new" => "users#create"
  get "/user/terms" => "users#terms"
  post "/user/save" => "users#save"
  get "/user/:display_name/confirm/resend" => "users#confirm_resend"
  match "/user/:display_name/confirm" => "users#confirm", :via => [:get, :post]
  match "/user/confirm" => "users#confirm", :via => [:get, :post]
  match "/user/confirm-email" => "users#confirm_email", :via => [:get, :post]
  post "/user/go_public" => "users#go_public"
  match "/user/reset-password" => "users#reset_password", :via => [:get, :post]
  match "/user/forgot-password" => "users#lost_password", :via => [:get, :post]
  get "/user/suspended" => "users#suspended"

  get "/index.html", :to => redirect(:path => "/")
  get "/create-account.html", :to => redirect(:path => "/user/new")
  get "/forgot-password.html", :to => redirect(:path => "/user/forgot-password")

  # omniauth
  get "/auth/failure" => "users#auth_failure"
  match "/auth/:provider/callback" => "users#auth_success", :via => [:get, :post], :as => :auth_success
  match "/auth/:provider" => "users#auth", :via => [:get, :post], :as => :auth

  # permalink
  get "/go/:code" => "site#permalink", :code => /[a-zA-Z0-9_@~]+[=-]*/

  # rich text preview
  post "/preview/:type" => "site#preview", :as => :preview

  # traces
  resources :traces, :except => [:show]
  get "/user/:display_name/traces/tag/:tag/page/:page" => "traces#index", :page => /[1-9][0-9]*/
  get "/user/:display_name/traces/tag/:tag" => "traces#index"

app/controllers/api/traces_controller.rb
module Api
  class TracesController < ApiController
    layout "site", :except => :georss

    before_action :authorize_web
    before_action :set_locale
    before_action :authorize

    authorize_resource

    before_action :check_database_readable, :except => [:show, :data]
    before_action :check_database_writable, :only => [:create, :update, :destroy]
    before_action :check_api_readable, :only => [:show, :data]
    before_action :check_api_writable, :only => [:create, :update, :destroy]
    before_action :offline_redirect, :only => [:create, :destroy, :data]
    around_action :api_call_handle_error

    def show
      @trace = Trace.visible.find(params[:id])

      head :forbidden unless @trace.public? || @trace.user == current_user
    end

    def update
      trace = Trace.visible.find(params[:id])

      if trace.user == current_user
        trace.update_from_xml(request.raw_post)
        trace.save!

        head :ok
      else
        head :forbidden
      end
    end

    def destroy
      trace = Trace.visible.find(params[:id])

      if trace.user == current_user
        trace.visible = false
        trace.save!
        TraceDestroyerJob.perform_later(trace) if Settings.trace_use_job_queue

        head :ok
      else
        head :forbidden
      end
    end

    def data
      trace = Trace.visible.find(params[:id])

      if trace.public? || trace.user == current_user
        if request.format == Mime[:xml]
          send_data(trace.xml_file.read, :filename => "#{trace.id}.xml", :type => request.format.to_s, :disposition => "attachment")
        elsif request.format == Mime[:gpx]
          send_data(trace.xml_file.read, :filename => "#{trace.id}.gpx", :type => request.format.to_s, :disposition => "attachment")
        else
          send_file(trace.trace_name, :filename => "#{trace.id}#{trace.extension_name}", :type => trace.mime_type, :disposition => "attachment")
        end
      else
        head :forbidden
      end
    end

    def create
      tags = params[:tags] || ""
      description = params[:description] || ""
      visibility = params[:visibility]

      if visibility.nil?
        visibility = if params[:public]&.to_i&.nonzero?
                       "public"
                     else
                       "private"
                     end
      end

      if params[:file].respond_to?(:read)
        trace = do_create(params[:file], tags, description, visibility)

        if trace.id
          TraceImporterJob.perform_later(trace) if Settings.trace_use_job_queue
          render :plain => trace.id.to_s
        elsif trace.valid?
          head :internal_server_error
        else
          head :bad_request
        end
      else
        head :bad_request
      end
    end

    private

    def do_create(file, tags, description, visibility)
      # Sanitise the user's filename
      name = file.original_filename.gsub(/[^a-zA-Z0-9.]/, "_")

      # Get a temporary filename...
      filename = "/tmp/#{rand}"

      # ...and save the uploaded file to that location
      File.open(filename, "wb") { |f| f.write(file.read) }

      # Create the trace object, falsely marked as already
      # inserted to stop the import daemon trying to load it
      trace = Trace.new(
        :name => name,
        :tagstring => tags,
        :description => description,
        :visibility => visibility,
        :inserted => true,
        :user => current_user,
        :timestamp => Time.now.getutc
      )

      if trace.valid?
        Trace.transaction do
          begin
            # Save the trace object
            trace.save!

            # Rename the temporary file to the final name
            FileUtils.mv(filename, trace.trace_name)
          rescue StandardError
            # Remove the file as we have failed to update the database
            FileUtils.rm_f(filename)

            # Pass the exception on
            raise
          end

          begin
            # Clear the inserted flag to make the import daemon load the trace
            trace.inserted = false
            trace.save!
          rescue StandardError
            # Remove the file as we have failed to update the database
            FileUtils.rm_f(trace.trace_name)

            # Pass the exception on
            raise
          end
        end
      end

      # Finally save the user's preferred privacy level
      if pref = current_user.preferences.where(:k => "gps.trace.visibility").first
        pref.v = visibility
        pref.save
      else
        current_user.preferences.create(:k => "gps.trace.visibility", :v => visibility)
      end

      trace
    end

    def offline_redirect
      redirect_to :action => :offline if Settings.status == "gpx_offline"
    end
  end
end

app/helpers/trace_helper.rb
module TraceHelper
  def link_to_tag(tag)
    if @action == "mine"
      link_to(tag, :tag => tag, :page => nil)
    else
      link_to(tag, :tag => tag, :display_name => @display_name, :page => nil)
    end
  end
end

app/views/traces/_description.html.erb
<%= image_tag(url_for(:controller => :traces, :action => :icon, :id => description.id, :display_name => description.user.display_name)) %>
<% if description.size -%>
<%= t ".description_with_count", :count => description.size, :user => description.user.display_name %>
<% else -%>
<%= t ".description_without_count", :user => description.user.display_name %>
<% end -%>

app/views/traces/_trace.html.erb
<tr>
  <% cl = cycle("table0", "table1") %>
  <td class="<%= cl %>">
    <% if Settings.status != "gpx_offline" %>
      <% if trace.inserted %>
        <a href="<%= url_for :controller => "traces", :action => "show", :id => trace.id, :display_name => trace.user.display_name %>"><img src="<%= url_for :controller => "traces", :action => "icon", :id => trace.id, :display_name => trace.user.display_name %>" border="0" alt="" /></a>
      <% else %>
        <span class="trace_pending"><%= t ".pending" %></span>
      <% end %>
    <% end %>
  </td>
  <td class="<%= cl %>"><%= link_to trace.name, :controller => "traces", :action => "show", :display_name => trace.user.display_name, :id => trace.id %>
    <span class="trace_summary" title="<%= trace.timestamp %>"> ...
      <% if trace.inserted %>
        (<%= t ".count_points", :count => trace.size %>)
      <% end %>
      ... <%= time_ago_in_words(trace.timestamp, :scope => :'datetime.distance_in_words_ago') %></span>
      <%= link_to_if trace.inserted?, t(".map"), { :controller => "site", :action => "index", :mlat => trace.latitude, :mlon => trace.longitude, :anchor => "map=14/#{trace.latitude}/#{trace.longitude}" }, { :title => t(".view_map") } %> /
      <%= link_to t(".edit"), { :controller => "site", :action => "edit", :gpx => trace.id }, { :title => t(".edit_map") } %>
      <span class="trace_<%= trace.visibility %>"><%= t("." + trace.visibility) %></span>
      <br />
      <%= trace.description %>
    <br />
    <%= t ".by" %> <%= link_to h(trace.user.display_name), user_path(trace.user) %>
    <% if !trace.tags.empty? %>
      <%= t ".in" %>
      <%= raw(trace.tags.collect { |tag| link_to_tag tag.tag }.join(", ")) %>
    <% end %>
  </td>
</tr>

app/views/traces/_trace_paging_nav.html.erb
<p>

<% if @traces.size > 1 %>
<% if @page > 1 %>
<%= link_to t(".newer"), @params.merge(:page => @page - 1) %>
<% else %>
<%= t(".newer") %>
<% end %>

| <%= t(".showing_page", :page => @page) %> |

<% if @traces.size < @page_size %>
<%= t(".older") %>
<% else %>
<%= link_to t(".older"), @params.merge(:page => @page + 1) %>
<% end %>
<% end %>
</p>

app/views/traces/edit.html.erb
<% content_for :heading do %>
  <h2><%= t ".heading", :name => h(@trace.name) %></h2>
<% end %>

<img src="<%= url_for :controller => "traces", :action => "picture", :id => @trace.id, :display_name => @trace.user.display_name %>">

<%= form_for @trace do |f| %>

<div id='edit-trace-form' class='standard-form'>
  <fieldset>
    <div class='form-row'>
      <label class='standard-label'><%= t ".filename" %></label>
      <p class='deemphasize'><%= @trace.name %> (<%= link_to t(".download"), trace_data_path(@trace) %>)</p>
    </div>
    <div class='form-row'>
      <label class='standard-label'><%= t ".uploaded_at" %></label>
      <p class='deemphasize'><%= l @trace.timestamp, :format => :friendly %></p>
    </div>
  <% if @trace.inserted? %>
    <div class='form-row'>
      <label class='standard-label'><%= t ".points" %></label>
      <p class='deemphasize'><%= @trace.size.to_s.gsub(/(\d)(?=(\d{3})+$)/, '\1,') %></p>
    </div>
    <div class='form-row'>
      <label class='standard-label'><%= t ".start_coord" %></label>
    </div>
    <div class="geo">
      <span class="latitude"><%= @trace.latitude %></span>;
      <span class="longitude"><%= @trace.longitude %></span>
    </div>
    (<%= link_to t(".map"), :controller => "site", :action => "index", :anchor => "map=14/#{@trace.latitude}/#{@trace.longitude}" %> / <%= link_to t(".edit"), :controller => "site", :action => "edit", :gpx => @trace.id, :anchor => "map=14/#{@trace.latitude}/#{@trace.longitude}" %>)
  <% end %>
    <div class='form-row'>
      <label class='standard-label'><%= t ".owner" %></label>
      <p class='deemphasize'><%= link_to h(@trace.user.display_name), user_path(@trace.user) %></p>
    </div>
    <div class='form-row'>
      <label class='standard-label'><%= t ".description" %></label>
      <%= f.text_field :description %>
    </div>
    <div class='form-row'>
      <label class='standard-label'><%= t ".tags" %></label>
      <%= f.text_field :tagstring %> (<%= t ".tags_help" %>)
    </div>
    <div class='form-row'>
      <label class='standard-label'><%= t ".visibility" %></label>
      <%= f.select :visibility, [[t("traces.visibility.private"), "private"], [t("traces.visibility.public"), "public"], [t("traces.visibility.trackable"), "trackable"], [t("traces.visibility.identifiable"), "identifiable"]] %> (<a href="<%= t ".visibility_help_url" %>"><%= t ".visibility_help" %></a>)
    </div>
  </fieldset>

</div>

<%= f.submit %>

<% end %>

app/views/traces/index.html.erb
<% content_for :heading do %>
  <h1><%= h(@title) %></h1>
  <ul class='secondary-actions clearfix'>
    <li><%= t(".description") %></li>
    <li><%= rss_link_to :action => "georss", :display_name => @display_name, :tag => @tag %></li>
    <li><%= link_to t(".upload_trace"), new_trace_path %></li>
    <% if @tag %>
      <li><%= link_to t(".see_all_traces"), :controller => "traces", :action => "index", :display_name => nil, :tag => nil, :page => nil %></li>
      <li><%= link_to t(".see_my_traces"), :action => "mine", :tag => nil, :page => nil %></li>
    <% else %>
      <% if @display_name %>
        <li><%= link_to t(".see_all_traces"), :controller => "traces", :action => "index", :display_name => nil, :tag => nil, :page => nil %></li>
      <% end %>
      <% if current_user && current_user != @target_user %>
        <li><%= link_to t(".see_my_traces"), :action => "mine", :tag => nil, :page => nil %></li>
      <% end %>
    <% end %>
  </ul>
<% end %>

<% content_for :auto_discovery_link_tag do %>
<%= auto_discovery_link_tag :rss, :action => "georss", :display_name => @display_name, :tag => @tag %>
<% end %>

<% if @traces.size > 0 %>
  <%= render :partial => "trace_paging_nav" %>

  <table id="trace_list" cellpadding="3">
    <thead>
      <tr>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <%= render @traces unless @traces.nil? %>
    </tbody>
  </table>

  <%= render :partial => "trace_paging_nav" %>
<% else %>
  <h4><%= t ".empty_html", :upload_link => new_trace_path %></h4>
<% end %>

app/views/traces/new.html.erb
<% content_for :heading do %>
  <h1><%= t ".upload_trace" %></h1>
<% end %>

<%= error_messages_for "trace" %>

<%= form_for @trace, :url => { :action => "create" }, :html => { :multipart => true } do |f| %>
  <div class="standard-form">
    <fieldset>
      <div class='form-row'>
        <label for="trace_gpx_file" class="standard-label"><%= t ".upload_gpx" %></label>
        <%= f.file_field :gpx_file %>
      </div>
      <div class='form-row'>
        <label class="standard-label"><%= t ".description" %></label>
        <%= f.text_field :description %>
      </div>
      <div class='form-row'>
        <label class="standard-label"><%= t ".tags" %></label>
        <%= f.text_field :tagstring %>
        <span class="form-help deemphasize">(<%= t ".tags_help" %>)</span>
      </div>
      <div class='form-row'>
        <label class="standard-label"><%= t ".visibility" %></label>
        <%= f.select :visibility, [[t("traces.visibility.private"), "private"], [t("traces.visibility.public"), "public"], [t("traces.visibility.trackable"), "trackable"], [t("traces.visibility.identifiable"), "identifiable"]] %>
        <span class="form-help deemphasize">(<a href="<%= t ".visibility_help_url" %>"><%= t ".visibility_help" %></a>)</span>
      </div>
    </fieldset>

    <%= f.submit %>
    <span class="form-help deemphasize"><a href="<%= t ".help_url" %>"><%= t ".help" %></a></span>
  </div>
<% end %>

app/views/traces/offline.html.erb
<% content_for :heading do %>
<h2><%= t ".heading" %></h2>
<% end %>

<p><%= t ".message" %></p>

app/views/traces/show.html.erb
<% content_for :heading do %>
  <h2><%= t ".heading", :name => h(@trace.name) %></h2>
<% end %>

<% if Settings.status != "gpx_offline" %>
  <% if @trace.inserted %>
    <img src="<%= url_for :controller => "traces", :action => "picture", :id => @trace.id, :display_name => @trace.user.display_name %>">
  <% else %>
    <span class="trace_pending"><%= t ".pending" %></span>
  <% end %>
<% end %>

<table border="0">
  <tr>
    <td><%= t ".filename" %></td>
    <td><%= @trace.name %> (<%= link_to t(".download"), trace_data_path(@trace) %>)</td>
  </tr>
  <tr>
    <td><%= t ".uploaded" %></td>
    <td><%= l @trace.timestamp, :format => :friendly %></td>
  </tr>
  <% if @trace.inserted? %>
  <tr>
    <td><%= t ".points" %></td>
    <td><%= @trace.size.to_s.gsub(/(\d)(?=(\d{3})+$)/, '\1,') %></td></tr>
  <tr>
    <td><%= t ".start_coordinates" %></td>
    <td><div class="geo"><span class="latitude"><%= @trace.latitude %></span>; <span class="longitude"><%= @trace.longitude %></span></div> (<%= link_to t(".map"), :controller => "site", :action => "index", :mlat => @trace.latitude, :mlon => @trace.longitude, :anchor => "map=14/#{@trace.latitude}/#{@trace.longitude}" %> / <%= link_to t(".edit"), :controller => "site", :action => "edit", :gpx => @trace.id, :anchor => "map=14/#{@trace.latitude}/#{@trace.longitude}" %>)</td>
  </tr>
  <% end %>
  <tr>
    <td><%= t ".owner" %></td>
    <td><%= link_to h(@trace.user.display_name), user_path(@trace.user) %></td>
  </tr>
  <tr>
    <td><%= t ".description" %></td>
    <td><%= h(@trace.description) %></td>
  </tr>
  <tr>
    <td><%= t ".tags" %></td>
    <td>
    <% unless @trace.tags.empty? %>
      <%= raw(@trace.tags.collect { |tag| link_to tag.tag, :controller => "traces", :action => "index", :tag => tag.tag, :id => nil }.join(", ")) %>
    <% else %>
      <i><%= t ".none" %></i>
    <% end %>
    </td>
  </tr>
  <tr>
    <td><%= t ".visibility" %></td>
    <td><%= t "traces.visibility.#{@trace.visibility}" %></td>
  </tr>
</table>

<br /><br />

<% if current_user && (current_user==@trace.user || current_user.administrator? || current_user.moderator?) %>
  <div class="buttons">
    <% if current_user == @trace.user %>
      <%= link_to t(".edit_trace"), edit_trace_path(@trace), :class => "button" %>
    <% end %>
    <%= button_to t(".delete_trace"), { :controller => "traces", :action => "destroy", :id => @trace.id }, { :method => :delete, :data => { :confirm => t(".confirm_delete") } } %>
  </div>
<% end %>